// Code generated by "stringer -type=StatusCode"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-200]
	_ = x[CREATED-201]
	_ = x[ACCEPTED-202]
	_ = x[NO_CONTENT-204]
	_ = x[FOUND-302]
	_ = x[BAD_REQUEST-400]
	_ = x[UNAUTHORIZED-401]
	_ = x[FORBIDDEN-403]
	_ = x[NOT_FOUND-404]
	_ = x[METHOD_NOT_ALLOWED-405]
	_ = x[CONTENT_TOO_LARGE-413]
	_ = x[URI_TOO_LONG-414]
	_ = x[INTERNAL_SERVER_ERROR-500]
}

const (
	_StatusCode_name_0 = "OKCREATEDACCEPTED"
	_StatusCode_name_1 = "NO_CONTENT"
	_StatusCode_name_2 = "FOUND"
	_StatusCode_name_3 = "BAD_REQUESTUNAUTHORIZED"
	_StatusCode_name_4 = "FORBIDDENNOT_FOUNDMETHOD_NOT_ALLOWED"
	_StatusCode_name_5 = "CONTENT_TOO_LARGEURI_TOO_LONG"
	_StatusCode_name_6 = "INTERNAL_SERVER_ERROR"
)

var (
	_StatusCode_index_0 = [...]uint8{0, 2, 9, 17}
	_StatusCode_index_3 = [...]uint8{0, 11, 23}
	_StatusCode_index_4 = [...]uint8{0, 9, 18, 36}
	_StatusCode_index_5 = [...]uint8{0, 17, 29}
)

func (i StatusCode) String() string {
	switch {
	case 200 <= i && i <= 202:
		i -= 200
		return _StatusCode_name_0[_StatusCode_index_0[i]:_StatusCode_index_0[i+1]]
	case i == 204:
		return _StatusCode_name_1
	case i == 302:
		return _StatusCode_name_2
	case 400 <= i && i <= 401:
		i -= 400
		return _StatusCode_name_3[_StatusCode_index_3[i]:_StatusCode_index_3[i+1]]
	case 403 <= i && i <= 405:
		i -= 403
		return _StatusCode_name_4[_StatusCode_index_4[i]:_StatusCode_index_4[i+1]]
	case 413 <= i && i <= 414:
		i -= 413
		return _StatusCode_name_5[_StatusCode_index_5[i]:_StatusCode_index_5[i+1]]
	case i == 500:
		return _StatusCode_name_6
	default:
		return "StatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
